name: TestableMockingExample

options:
  developmentLanguage: en
  deploymentTarget:
    iOS: 15.0

packages:
  TestableMocking:
    path: ../

targets:
  TestableMockingExample:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: Info.plist
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: com.dev.TestableMockingExample
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
    sources:
      - TestableMockingExample
    dependencies:
      - package: TestableMocking
  TestableMockingExampleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - TestableMockingExampleTests
    settings:
      base:
        INFOPLIST_FILE: Info.plist
    dependencies:
      - package: TestableMocking
      - target: TestableMockingExample
